//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.04 at 03:02:24 PM CEST 
//


package com.mastercom.ps.connector.response.domain.casefiling;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseFilingData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseFilingData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="caseID" type="{}CaseID"/>
 *           &lt;element name="fileAttachment" type="{}fileAttachment"/>
 *           &lt;element name="caseFilingResponseList" type="{}CaseFilingResponseList" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseFilingData", propOrder = {
    "method",
    "caseID",
    "fileAttachment",
    "caseFilingResponseList"
})
public class CaseFilingData {

    @XmlElement(required = true)
    protected String method;
    protected CaseID caseID;
    protected FileAttachment fileAttachment;
    protected List<CaseFilingResponseList> caseFilingResponseList;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the caseID property.
     * 
     * @return
     *     possible object is
     *     {@link CaseID }
     *     
     */
    public CaseID getCaseID() {
        return caseID;
    }

    /**
     * Sets the value of the caseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseID }
     *     
     */
    public void setCaseID(CaseID value) {
        this.caseID = value;
    }

    /**
     * Gets the value of the fileAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link FileAttachment }
     *     
     */
    public FileAttachment getFileAttachment() {
        return fileAttachment;
    }

    /**
     * Sets the value of the fileAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileAttachment }
     *     
     */
    public void setFileAttachment(FileAttachment value) {
        this.fileAttachment = value;
    }

    /**
     * Gets the value of the caseFilingResponseList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseFilingResponseList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseFilingResponseList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseFilingResponseList }
     * 
     * 
     */
    public List<CaseFilingResponseList> getCaseFilingResponseList() {
        if (caseFilingResponseList == null) {
            caseFilingResponseList = new ArrayList<CaseFilingResponseList>();
        }
        return this.caseFilingResponseList;
    }

}
